
const materials = {

"N87":{curie:220,bmax:0.3},
"N97":{curie:210,bmax:0.32},
"PC40":{curie:230,bmax:0.35},
"3C90":{curie:215,bmax:0.3},
"3F3":{curie:230,bmax:0.35}

}

const cores = {

"ETD":[
{name:"ETD29",Ap:0.65,Ae:0.00007},
{name:"ETD39",Ap:2.4,Ae:0.000125},
{name:"ETD44",Ap:4.5,Ae:0.000173},
{name:"ETD49",Ap:7.8,Ae:0.000211},
{name:"ETD59",Ap:17,Ae:0.000368}
],

"EE":[
{name:"EE30",Ap:1.1,Ae:0.00009},
{name:"EE40",Ap:2.6,Ae:0.000125},
{name:"EE55",Ap:7.5,Ae:0.00025}
]

}

const awg = {

"20":0.81,
"22":0.64,
"24":0.51,
"26":0.40,
"28":0.32,
"30":0.25

}

function calculate(){

let Vin=parseFloat(document.getElementById("vin").value)
let Vout=parseFloat(document.getElementById("vout").value)
let f=parseFloat(document.getElementById("freq").value)*1000
let P=parseFloat(document.getElementById("power").value)

let coretype=document.getElementById("coretype").value
let material=document.getElementById("material").value

let Bmax=materials[material].bmax

let Kw=0.4
let Ku=0.3
let J=4000000

let Ap=P/(Kw*Ku*Bmax*J*f)

let corelist=cores[coretype]

let suggestions=""

for(let c of corelist){

if(c.Ap>=Ap){

suggestions+=c.name+"<br>"

}

}

let Ae=corelist[0].Ae

let Buser=0.2

let Np=Vin/(4*f*Buser*Ae)
let Ns=Np*(Vout/Vin)

let freqk=document.getElementById("freq").value

let skindepth=66/Math.sqrt(freqk)

let maxwire=2*skindepth

let result=`

Minimum Area Product: ${Ap.toFixed(4)} m^4 <br><br>

Possible Cores:<br>
${suggestions}

<br>

Curie Temperature: ${materials[material].curie} °C <br>
Maximum Flux Density: ${Bmax} T <br>

<br>

Primary Turns: ${Math.round(Np)} <br>
Secondary Turns: ${Math.round(Ns)} <br>

<br>

Skin Depth: ${skindepth.toFixed(3)} mm <br>
Maximum Wire Diameter: ${maxwire.toFixed(3)} mm

`

document.getElementById("results").innerHTML=result

}

function generatePDF(){

const {jsPDF}=window.jspdf

let doc=new jsPDF()

doc.text("High Frequency Transformer Design",20,20)

doc.text("Generated by AJ Electronics",20,30)

doc.text("https://aj-electronics.github.io/High_Frequency_Transformer_Calculator/",20,40)

let text=document.getElementById("results").innerText

doc.text(text,20,60)

doc.save("transformer_design.pdf")

}